apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: embeddings-worker
  name: embeddings-worker
spec:
  replicas: {{ .Values.embeddingsWorkerReplicas }}
  selector:
    matchLabels:
      io.kompose.service: embeddings-worker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: embeddings-worker
    spec:
      containers:
      - args:
        - celery
        - worker
        - --app=embeddings_worker.app
        - --queues=embeddings
        - -BE
        env:
        - name: CELERY_BROKER_URL
          value: {{ .Values.redisUrl }}
        - name: CELERY_RESULT_BACKEND
          value: {{ .Values.celeryResultBackend }}
        - name: prometheus_multiproc_dir
          value: /prometheus_multiproc_dir
        - name: REDIS_HOST
          value: {{ .Values.redisHost }}
        image: edzia/lsdp-app
        name: embeddings-worker
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: embeddings-worker-claim0
        - mountPath: /prometheus_multiproc_dir
          name: embeddings-worker-claim1
      restartPolicy: Always
      volumes:
      - name: embeddings-worker-claim0
        hostPath:
          path: {{ .Values.appPath }}
      - name: embeddings-worker-claim1
        hostPath:
          path: {{ .Values.prometheusMultiprocDirPath }}
status: {}
