apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      nodeName: ip-172-31-25-8
      containers:
      - args:
        - mongod
        - --auth
        env:
        - name: MONDODB_LOG_DIR
          value: /dev/null
        - name: MONGODB_DATA_DIR
          value: /data/db
        - name: MONGO_INITDB_DATABASE
          value: reddit
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: toor
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init-mongo.js
          name: mongodb-claim0
          readOnly: true
        - mountPath: /data/db
          name: mongodb-claim1
      restartPolicy: Always
      volumes:
      - name: mongodb-claim0
        hostPath:
          path: {{ .Values.initMongoPath }}
      - name: mongodb-claim1
        hostPath:
          path: {{ .Values.mongoPath }}
status: {}
