apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis:3.0-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        args:
          - redis-server
          - /etc/redis/redis.conf
        volumeMounts:
          - name: redis-config
            mountPath: /etc/redis/redis.conf
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: redis-config
          hostPath:
            path: {{ .Values.redisConfigPath }}
status: {}
