apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: scraping-worker
  name: scraping-worker
spec:
  replicas: {{ .Values.scrapingWorkersReplicas }}
  selector:
    matchLabels:
      io.kompose.service: scraping-worker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: scraping-worker
    spec:
      nodeName: ip-172-31-16-35
      containers:
      - args:
        - celery
        - worker
        - --app=scraping_worker.app
        - --queues=scraping
        - -BE
        env:
        - name: CELERY_BROKER_URL
          value: {{ .Values.redisUrl }}
        - name: CELERY_RESULT_BACKEND
          value: {{ .Values.celeryResultBackend }}
        - name: prometheus_multiproc_dir
          value: /prometheus_multiproc_dir
        - name: REDIS_HOST
          value: {{ .Values.redisHost }}
        image: edzia/lsdp-app
        name: scraping-worker
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: scraping-worker-claim0
        - mountPath: /prometheus_multiproc_dir
          name: scraping-worker-claim1
      restartPolicy: Always
      volumes:
      - name: scraping-worker-claim0
        hostPath:
          path: {{ .Values.appPath }}
      - name: scraping-worker-claim1
        hostPath:
          path: {{ .Values.prometheusMultiprocDirPath }}
status: {}
