global:
  scrape_interval: 30s

scrape_configs:
  - job_name: worker
    scrape_interval: 30s
    metrics_path: 'metrics'
    static_configs:
      - targets:
        - metrics:8080

  - job_name: celery
    scrape_interval: 30s
    metrics_path: 'celery-metrics'
    static_configs:
      - targets:
        - celery-metrics:9540
